---
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.app_name}}
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "{{.Values.app_name}}"
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    k8s-app: {{.Values.app_name}}